import "@/app/globals.css";
import { Forum, Lora } from "next/font/google";
import { ModalWindowProvider } from "@/contexts/ModalWindowContext.jsx";
import { Container } from "@/components/ui/Container";

// const inter = Inter({ subsets: ["latin"] });

const forum = Forum({
  subsets: ["latin", "cyrillic"],
  variable: "--font-forum",
  weight: "400",
});

const lora = Lora({
  subsets: ["latin", "cyrillic"],
  variable: "--font-lora",
});

export const metadata = {
  title: {
    default: "Mvila",
    template: "%s | Mvila",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className={`${forum.variable} ${lora.variable} font-serif`}>
      <body className="flex min-h-screen flex-col bg-cBeige1 text-[#202020]">
        {/* <Container> */}
        <ModalWindowProvider>{children}</ModalWindowProvider>
        {/* </Container> */}
      </body>
    </html>
  );
}
